"""
Created on Fri May 14 13:43:50 2021

@author: Fogol

Project Euler Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

i = 1
j = 2
k = 2
sum = 0

while i < 4000000 and j <4000000:

    if k % 2 == 0:
            sum = sum + k
            
    k= i + j
    
    if i < j:
        i = k
    else:
        j = k
        
print('Fibonacci Number :', k)
print('Sum of Even Numbers :', sum)